# Generated by Django 2.2.5 on 2019-09-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190914_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
